### ISSUE TITLE
RestSharp sends `Content-Length: 0` under mono

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1081]
I suspect that its always set, but .net does a cleanup before sending it, making this an issue only for users running under mono. The issue exposes itself when connecting to qBittorrent as it returns a 400 response when the extraneous header is included and a proper response when it is missing.

Perhaps this is the last push we need to retire RestSharp.

**Comment by BlairEh** [comment]
Is there a way then to get around the version check? Is that the only REST query to qBittorrent?

**Comment by markus101** [comment]
No way around it and its not the only request, it just happens to be the first request.

**Comment by thezoggy** [comment]
old mono code where bug prob is:
https://github.com/mono/mono/commit/f647afb02fea54af468d2f164263cae1582d6736

looking at latest mono code, looks like that logic all changed a bit.. 
https://github.com/mono/mono/blob/master/mcs/class/System/System.Net/HttpWebRequest.cs#L183

wonder what the actual header qbittorrent sends.. if its in the same name/case that .net expects it to be..

**Comment by minakitty** [comment]
Which makes this a problem for anyone using Sonarr+qBittorent+Linux, like myself.  I've been changing my protocols up while moving to a new system because I want to use SOCKS5 for my downloads.  Transmission has no proxy support, Deluge's seems to be broken (I lose all connectivity when I turn on the proxy) so I'm quickly running out of options.  Is there a way to have Sonarr just log the errors and ignore?

**Comment by elBradford** [comment]
@minakitty I'm in the same boat, waiting for a fix. I guess I could dive in and do a patch, but I'm pretty inexperienced. I'm using qBittorrent because it will bind to an interface (tun0, OpenVPN), so a similar situation to you. If we can't fix it in this version, logging the error and ignoring sounds like a reasonable stopgap to me.

**Comment by markus101** [comment]
> Is there a way to have Sonarr just log the errors and ignore?
> logging the error and ignoring sounds like a reasonable stopgap to me.

No thats not possible, qBittorent is failing, not Sonarr, an acceptable work around would be to use Torrent Blackhole. From what I've read on in the HTTP spec its a grey area whether it should be accepted or not other clients don't care, but qBittorent is being more strict. In this case its likely more mono not handling it correctly, but we'll do what we can to correct it, when we can.

**Comment by elBradford** [comment]
@markus101 Thanks for the blackhole tip.

**Comment by dsemi** [comment]
It's weird that the behavior isn't consistent under mono, but it seems like qBittorrent should be able to handle the case where content-length is 0.  
Looking [here](https://github.com/qbittorrent/qBittorrent/blob/2aa8c07d0e00770929d15d695062154578dfb53f/src/base/http/requestparser.cpp#L82), it seems like they try to parse the message when the content-length header exists at all, and would result in a 400 error if the length was 0.  The fix could be as simple as skipping that block if the length is 0 as well. Not sure if anything else would need to be changed.

**Comment by dsemi** [comment]
Created a [pull request](https://github.com/qbittorrent/qBittorrent/pull/4833) to not try to parse the empty message; when I built locally, Sonarr was able to pass the test when adding qBittorrent as a download client.

**Comment by thezoggy** [comment]
https://github.com/qbittorrent/qBittorrent/issues/2482

**Comment by Fastjur** [comment]
This issue is affecting me aswell. Currently qBittorrent is unusable with Sonarr on Linux

**Comment by elBradford** [comment]
As was suggested, I used torrent black hole, and it's working very well for me at the moment. I look forward to this being fixed, but in the mean time you can use qBittorrent and Sonarr together using this method.

Date: Thu, 25 Feb 2016 08:08:29 -0800

**Comment by Fastjur** [comment]
Yes that is true. I currently have deluge setup. But I prefer 
qBittorrent. I will wait until it is fixed and then switch I think.

**Comment by Patthe** [comment]
Same issue. Waiting for a fix.

**Comment by dsemi** [comment]
My [pull request](https://github.com/qbittorrent/qBittorrent/pull/4833) has been merged. Whenever the next version of qBittorrent is released, it should be fixed.

**Comment by Taloth** [comment]
I also have a branch (qbittorrent-http-client = https://github.com/Sonarr/Sonarr/pull/1166) that deals with it on our end, but it's totally untested, bleeding edge stuff. That PR affects every download client, so needs different devs to test all combos.

**Comment by Fastjur** [comment]
@dsemi I updated to the latest version of qBittorrent using `sudo apt-get update && sudo apt-get install qbittorrent-nox`

However I still get the issue `Unknown exception: REST request failed: [400] [GET] at [http://localhost:8112/version/api]`. When I navigate to the that URL in my browser, it seems to work fine and it prints out `8`.

Does it work for you with the latest version?

**Comment by markus101** [comment]
No longer using RestSharp for Download Client communication in the latest develop builds.
