### ISSUE TITLE
Can't connect to Rtorrent- same settings work fine in Radarr

### ISSUE THREAD

**Issue by antigravity83** [Sonarr/Sonarr#2090]
Hi there

Rtorrent has been working great with Sonarr, then all of a sudden, it won't connect. 

Settings in Sonarr or Rtorrent haven't changed- and the same settings still work in Radarr.

**VERSION**
OS: Ubuntu 10.04
Version 2.0.0.4913
Mono Version 5.0.1.1
AppData directory /home/media/.config/NzbDrone
Startup directory /opt/NzbDrone

**Log Pastebin:** 
https://pastebin.com/WjKsS3eq

**Sonarr Settings:** 
http://imgur.com/a/eyj1k

Thanks

**Comment by markus101** [comment]
Update to 2.0.0.4919 which should fix this issue.

**Comment by antigravity83** [comment]
Still doesn't work on 2.0.0.4919

Deleted Download Client and readded, and also restarted Sonarr. Still doesn't work.

**Comment by markus101** [comment]
What do the logs show?
Restart Sonarr and check the trace logs for `Curl not available, using default WebClient.` (logged once after startup)

**Comment by antigravity83** [comment]
Changed to Trace logs, but can't see "Curl not available, using default WebClient" after restart

https://pastebin.com/vvZraWx1

**Comment by markus101** [comment]
Sorry, I should have also said, also try connecting to rtorrent.

**Comment by antigravity83** [comment]
Tried to connect to Rtorrent with Trace logs, but still can't see any "Curl not available, using default WebClient"

**Comment by antigravity83** [comment]
Here are the trace logs after a restart: https://pastebin.com/9hpF6VvA

And when I try to connect to RTorrent: https://pastebin.com/1MpzjEUp

I searched for the entire trace log for the text "Curl" and didn't get a response

**Comment by markus101** [comment]
Sorry as Taloth mentioned on the forums rTorrent doesn't fallback to curl and with Sonarr defaulting to the legacy TLS provider in mono currently (will be changed in the next release), it won't work with TLS 1.1 or 1.2 as well as newer ciphers. There will likely be a fix for that issue today, whatever update comes after 2.0.0.4919 should have it fixed whether that's out today or tomorrow.

If you're still having issues after that, please open a thread on the forums (or respond to your existing one and we'll take a look).

**Comment by antigravity83** [comment]
Hi guys- thanks seems to be working now after updating to 2.0.0.4928

Many thanks for the quick fix!
