### ISSUE TITLE
REPACK not being grabbed

### ISSUE THREAD

**Issue by jimbobjonesbob** [Sonarr/Sonarr#3250]
REPACK is not being snatched in v3 (and I've tested in v2 and it works with the same profiles etc).

Current file: Euphoria.US.S01E08.And.Salt.the.Earth.Behind.You.1080p.AMZN.WEB-DL.DDP5.1.H.264-KiNGS.mkv
Repack: Euphoria.US.S01E08.REPACK.And.Salt.the.Earth.Behind.You.1080p.AMZN.WEB-DL.DDP5.1.H.264-KiNGS.mkv

![sonarr3](https://user-images.githubusercontent.com/53840892/62584722-21814c00-b8f9-11e9-8e80-150382179228.png)
![sonarr2](https://user-images.githubusercontent.com/53840892/62584723-2219e280-b8f9-11e9-9d3e-2b5897183b6f.jpg)

The same profile will snatch the repack in v2, but if I change the minimum cutoff to webdl in v3 it will get it.

**Logs**
19-8-7 09:16:58.2|Debug|DownloadDecisionMaker|Processing release 'Euphoria.US.S01E08.REPACK.And.Salt.the.Earth.Behind.You.1080p.AMZN.WEB-DL.DDP5.1.H.264-KiNGS' from 'Hydra2'
19-8-7 09:16:58.2|Debug|Parser|Parsing string 'Euphoria.US.S01E08.REPACK.And.Salt.the.Earth.Behind.You.1080p.AMZN.WEB-DL.DDP5.1.H.264-KiNGS'
19-8-7 09:16:58.2|Debug|Parser|Episode Parsed. Euphoria US - S01E08 
19-8-7 09:16:58.2|Debug|Parser|Language parsed: English
19-8-7 09:16:58.2|Debug|QualityParser|Trying to parse quality for Euphoria.US.S01E08.REPACK.And.Salt.the.Earth.Behind.You.1080p.AMZN.WEB-DL.DDP5.1.H.264-KiNGS
19-8-7 09:16:58.3|Debug|Parser|Quality parsed: WEBDL-1080p v2
19-8-7 09:16:58.3|Debug|Parser|Release Group parsed: KiNGS
19-8-7 09:16:58.3|Debug|AlreadyImportedSpecification|Performing already imported check on report
19-8-7 09:16:58.3|Debug|UpgradableSpecification|New quality is a better revision for existing quality
19-8-7 09:16:58.3|Debug|UpgradeAllowedSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
19-8-7 09:16:58.3|Debug|UpgradableSpecification|At least one profile allows upgrading
19-8-7 09:16:58.3|Debug|AcceptableSizeSpecification|Beginning size check for: Euphoria.US.S01E08.REPACK.And.Salt.the.Earth.Behind.You.1080p.AMZN.WEB-DL.DDP5.1.H.264-KiNGS
19-8-7 09:16:58.3|Debug|AcceptableSizeSpecification|Item: Euphoria.US.S01E08.REPACK.And.Salt.the.Earth.Behind.You.1080p.AMZN.WEB-DL.DDP5.1.H.264-KiNGS, meets size constraints.
19-8-7 09:16:58.3|Debug|CutoffSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
19-8-7 09:16:58.3|Debug|UpgradableSpecification|Comparing preferred word score. Current: 0 New: 0
19-8-7 09:16:58.3|Debug|UpgradableSpecification|Existing item meets cut-off. skipping.
19-8-7 09:16:58.3|Debug|CutoffSpecification|Cutoff already met, rejecting.
19-8-7 09:16:58.3|Debug|MaximumSizeSpecification|Maximum size is not set.
19-8-7 09:16:58.3|Debug|LanguageSpecification|Checking if report meets language requirements. English
19-8-7 09:16:58.3|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: Euphoria.US.S01E08.REPACK.And.Salt.the.Earth.Behind.You.1080p.AMZN.WEB-DL.DDP5.1.H.264-KiNGS
19-8-7 09:16:58.3|Debug|ReleaseRestrictionsSpecification|[Euphoria.US.S01E08.REPACK.And.Salt.the.Earth.Behind.You.1080p.AMZN.WEB-DL.DDP5.1.H.264-KiNGS] No restrictions apply, allowing
19-8-7 09:16:58.3|Debug|QualityAllowedByProfileSpecification|Checking if report meets quality requirements. WEBDL-1080p v2
19-8-7 09:16:58.3|Debug|MinimumAgeSpecification|Minimum age is not set.
19-8-7 09:16:58.3|Debug|RetentionSpecification|Checking if report meets retention requirements. 0
19-8-7 09:16:58.4|Debug|UpgradeDiskSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
19-8-7 09:16:58.4|Debug|UpgradableSpecification|New item has a better quality revision
19-8-7 09:16:58.4|Debug|SeriesSpecification|Checking if series matches searched series
19-8-7 09:16:58.4|Debug|DelaySpecification|Ignoring delay for user invoked search
19-8-7 09:16:58.4|Debug|HistorySpecification|Skipping history check during search
19-8-7 09:16:58.4|Debug|MonitoredEpisodeSpecification|Skipping monitored check during search
19-8-7 09:16:58.4|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Existing file meets cutoff: HDTV-1080p - English

**System Information**

 - Sonarr Version: 3.0.2.564
 - Operating System: Windows 8.1
 - .net Framework (Windows) or mono (macOS/Linux) Version: 4.7.2

**Comment by markus101** [comment]
The existing file is `HDTV 1080p` according to the logs: `Existing file meets cutoff: HDTV-1080p - English`, Sonarr won't perform an upgrade to a repack in that case (as the cutoff has been met).

Sounds like during import (or afterwards during a rescan) the file is detected as HDTV 1080p. If you need help troubleshooting that, open a thread on the forums or subreddit, but closing this as it's not a bug based on the logs.

**Comment by jimbobjonesbob** [comment]
The existing file with the same profile gets the repack successfully in v2.

**Comment by markus101** [comment]
Because your v2 instance sees it as WEB DL 1080p. If you fix that in your v3 instance it'll work too.

**Comment by jimbobjonesbob** [comment]
![sonarr4](https://user-images.githubusercontent.com/53840892/62585563-ba659680-b8fc-11e9-8994-f049b75c07da.jpg)

**Comment by jimbobjonesbob** [comment]
Also, if v3 was seeing it as HDTV (which it isn't), then why when changing the cutoff in the profile to WEBDL would it then download the WEBDL REPACK? haha.

**Comment by markus101** [comment]
I was looking at this again and it looks like there is actually something wrong, just caught the wrong part of the log.

> changing the cutoff in the profile to WEBDL would it then download the WEBDL REPACK

That's definitely helpful and the underlying issue that I uncovered.

> haha.

And unhelpful...

**Comment by jimbobjonesbob** [comment]
It was all in the opening post "The same profile will snatch the repack in v2, but if I change the minimum cutoff to webdl in v3 it will get it."

**Comment by markus101** [comment]
Yeah, I missed that in the wall of logs (and a great example why we ask for a link, not them inline), but I digress, glad to have the logs.

**Comment by jimbobjonesbob** [comment]
Got the update that was pushed through:
Release is a repack for a different release group. Release Group: KiNGS. File release group: KiNGS
https://pastebin.com/GJnsxFak

**Comment by markus101** [comment]
That's just a logging issue, in both cases it's logging the release's release group instead of the file's release group, we'll fix that up.

**Comment by jimbobjonesbob** [comment]
Just got 3.0.2.572.

It still is not getting the repack FYI. 
https://pastebin.com/rZvZJPe2
19-8-10 08:26:20.8|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Release is a repack for a different release group. Release Group: KiNGS. File release group: KiNGS**a**

The 'a' after Kings is also in the logs.

![bleh](https://user-images.githubusercontent.com/53840892/62812483-40761d00-bb49-11e9-8bc5-2b776e86af86.jpg)

When you said it's just a logging issue, did you mean it should be getting repacks? I don't follow.

**Comment by markus101** [comment]
If the release group is the same, yes, in this case Sonarr parsed the existing release group as `KiNGSa` not `KiNGs`, but we have no insight into why. The two issues reported here have been addressed and this would be a new issue, but only the logs from when it was imported would be useful. If you see the wrong release group being parsed again and have the logs for it then a new issue would be warranted, but as it stands right now Sonarr is behaving correctly (and logging the correct thing).

**Comment by jimbobjonesbob** [comment]
How have the issues been addressed? I posted that sonarr is not getting repacks, and I'm using the exact same files as in the OP. And it still won't get repacks. And in between you working on it, sonarr has now added an 'a' to the release.

**Comment by markus101** [comment]
It's not grabbing it because the release group is not the same, that is not a bug. The logging isn't adding an arbitrary `a` after the release group, so it's not a logging issue that was related to the original issue.

Regardless of Sonarr not grabbing the repack the issue is no longer it not grabbing the repack from an issue with the processing of the repack, if there is a bug it's because the parser parsed the wrong release group, but that is a separate issue, which we'd need logs from the import to diagnose.
