### ISSUE TITLE
Synology DownloadStation API Breaking Change | Downloads cannot be added to Download Station

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#4388]
### It is advised users use a different download client at this time or if possible downgrade DownloadStation.  It is not known when or even if this can be fixed.  Please do not comment on this GHI asking for updates or when this will be fixed.

**Describe the bug**

Synology Download Stations has updated recently that appears to have has caused a breaking API change.  Torrents and NZBs (Usenet) are unable to be added to the client.

**To Reproduce**

N/A - Self Explanatory
**Expected behavior**

Downloads should be sent to the download client, Download Station, without errors.

**Screenshots**

**Platform Information (please complete the following information):**
 - OS:  Agnostic, download client bug
 - Docker:  Agnostic, download client bug
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status):  Agnostic, download client bug
 - Browser and Version (Only needed for UI issues):  Agnostic, download client bug
 - Sonarr Version:  Agnostic, download client bug.  broken on v2 and v3 through at least current develop, 3.0.5.1161
 - Sonarr Branch: Agnostic, download client bug
 - DSM Version: DSM 6.2.3-25426
 - DS Version: 3.8.16-3566
 - DS Hardware: DS1817+

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
```
21:03:14.1|Info|UsenetDownloadStation|Adding report [10 (1080p)] to the queue.21-3-17 21:03:14.2|Debug|DownloadStationTaskProxy|Trying to add task from data 10 (1080p).nzb21-3-17 21:03:14.2|Error|DownloadStationTaskProxy|Failed to add task from data 10 (1080p).nzb. Reason: Invalid parameter21-3-17 21:03:14.2|Warn|ProcessDownloadDecisions|Couldn't add report to download queue. 10 (1080p)
[v3.0.5.1144] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to add task from data 10 (1080p).nzb. Reason: Invalid parameterat NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T] (NzbDrone.Common.Http.HttpRequestBuilder requestBuilder, System.String operation, NzbDrone.Core.Download.Clients.DownloadStation.DiskStationApi api, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x000e8] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:125at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T] (NzbDrone.Common.Http.HttpRequestBuilder requestBuilder, System.String operation, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:66at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DownloadStationTaskProxy.AddTaskFromData (System.Byte[] data, System.String filename, System.String downloadDirectory, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x00038] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DownloadStationTaskProxy.cs:36at NzbDrone.Core.Download.Clients.DownloadStation.UsenetDownloadStation.AddFromNzbFile (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode, System.String filename, System.Byte[] fileContent) [0x0001f] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\DownloadStation\UsenetDownloadStation.cs:172at NzbDrone.Core.Download.UsenetClientBase\1[TSettings].Download (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode) [0x001a9] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\UsenetClientBase.cs:81at NzbDrone.Core.Download.DownloadService.DownloadReport (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode) [0x0018f] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\DownloadService.cs:75at NzbDrone.Core.Download.ProcessDownloadDecisions.ProcessDecisions (System.Collections.Generic.List`1[T] decisions) [0x00104] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\ProcessDownloadDecisions.cs:77`
21-3-17 21:03:14.5|Debug|Api|[GET] /api/v3/log/file: 200.OK (3 ms)
```
References:
https://www.reddit.com/r/sonarr/comments/m79s4t/synologysonarr_failed_to_add_task_from_data/
https://www.reddit.com/r/radarr/comments/m717ny/radarr_not_sending_to_download_station/
https://www.reddit.com/r/radarr/comments/m742w1/downloadstationtaskproxy_giving_error_failed_to/
https://community.synology.com/enu/forum/1/post/130786
https://forums.sonarr.tv/t/failed-to-add-task-from-data-invalid-data/27920/6

Most Recent Synology DS API Doc is from 2014
https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/DownloadStation/All/enu/Synology_Download_Station_Web_API.pdf

Per https://www.synology.com/en-us/support/developer#tool no further updated documentation is available.

**Comment by Taloth** [comment]
@devSparkle

There has been a recent security update for Download Station (https://www.synology.com/en-global/security/advisory/Synology_SA_21_11) which could be involved here.

Is this reproducible consistently? And if so, is it possible to downgrade Download Station to confirm?
Secondly, I don't know how responsive synology technical support is. But this could be an unwanted side effect of that update.

In February there was a single post about Invalid Parameter regarding DSM7. But that could have a different cause (unless that user was somehow running a beta download station version)

**Comment by Turakam83** [comment]
I have this probleme since the update. You can download a previous version here : https://archive.synology.com/download/Package/DownloadStation

**Comment by bxlouis** [comment]
Does someone know which is the latest version that works?

**Comment by bakerboy448** [comment]
> Does someone know which is the latest version that works?

DS Version: 3.8.16-3566 Is the broken version
So any version just prior to that should be fine for this at least

**Comment by bxlouis** [comment]
> > Does someone know which is the latest version that works?
> 
> DS Version: 3.8.16-3566 Is the broken version
> So any version just prior to that should be fine for this at least

Well, I updated DS to 3.8.16-3566 early this week, hoping it would solve the issue, but I was experiencing the same issue already with at least 3.8.15-3563.

**Comment by baroninn** [comment]
im running synology  DS1817+
I downgraded/rollback download station to version: 3.8.15-3563
everything is working normal now.

**Comment by MattyJacques** [comment]
Running DS218Play with DSM 6.2.3-25426 Update 3
I seem to be able to add torrents, but not usenet downloads

**Comment by bakerboy448** [comment]
@MattyJacques DownloadStation's version is what matters here.  DSM not as much

**Comment by jby** [comment]
Just to clarify if someone else gets the message that you can't install an older version than what you have installed already:
You have to uninstall Download Station before you can install the older version - AND I'd say DON'T delete the database for Download Station when uninstalling, then you'll loose all your settings and current items.

**Comment by devSparkle** [comment]
_Sorry for the delay, didn't notice my pings._

It appears this issue is transversal and unrelated to DSM versions. After some initial research I've noted that not all types of torrents fail to be added, although I've yet to identify the critical difference between those that are accepted and those that are rejected.

Rest assured I am looking into this, and will come back with either an update or a pull request as soon as I've narrowed down the issue.

**Comment by denperss** [comment]
im getting the same error: Failed to add task from data filename.torrent. Reason: Invalid parameter
using ipt.

**Comment by bakerboy448** [comment]
Yes this is known and expected, due to Synology pushing a breaking change.

there's no need to continue reporting it's an issue at this time

thanks,

**Comment by seansfkelley** [comment]
Hey there, I maintain another program that uses the Synology API and your ticket was cross-linked to mine. I thought you might want to know that I opened an issue with Synology and [received a response including documentation for the new endpoint](https://github.com/seansfkelley/synology-download-manager/issues/177#issuecomment-822699863) they plan to use going forward. This might also fix any compatibility issues you have with DSM 7.0. I can't personally vouch that it works as advertised because I haven't yet had time to test it.

**Comment by Bre77** [comment]
While trying to work around this issue, I have found that webapi/DownloadStation/task.cgi works over GET using the "uri" parameter instead of file. All other parameters can stay the same. Using Download Station 3.9.0-4585 on DSM 7.0 beta.

**Comment by drloser123** [comment]
Any news?

**Comment by denperss11** [comment]
> Any news?

Downgrade to last vers then it works again

**Comment by FloydKulis** [comment]
I cannot install the previous DS version on DSM 7.0.

**Comment by bakerboy448** [comment]
> I cannot install the previous DS version on DSM 7.0.

This was fixed 6 days ago

**Comment by FloydKulis** [comment]
> > I cannot install the previous DS version on DSM 7.0.
> 
> This issue was fixed and closed 6 days ago
> 
> and not surprised that you cannot downgrade...but all of this is a Synology problem 🤷‍♂️

Thank you very much for your answer. Now I can see something has improved. I have to check if it works. You don't know if this has also been implemented in Radarr?

**Comment by konfiot** [comment]
Wait shouldn't this be opened ?

**Comment by bakerboy448** [comment]
> Wait shouldn't this be opened ?

Why it was fixed and merged into nightly over a month ago?

**Comment by konfiot** [comment]
Ah yep, sorry, thought it would have landed in main by now and that it was still not working, but no, just had to pull develop, sorry for the inconvenience...

**Comment by Dudleydogg** [comment]
I see all the comments saying this is fixed, Can I presume to install DSM version 7 and Latest Download Station and all is well?

**Comment by drloser123** [comment]
> I see all the comments saying this is fixed, Can I presume to install DSM version 7 and Latest Download Station and all is well?

I did... And I had to rollback to the previous Download Station version.

**Comment by konfiot** [comment]
You also have to use the develop version of Sonarr, it still hasn't reached main

**Comment by Dudleydogg** [comment]
I have DSM 6.2.3-25426 using Download station Version 3.8.16-3566, I get Invalid when trying to add anything,  IF I manually add a NZB it will download but I have to manually insert to Radarr.  IF i downgrade Download station to 3.8.15 it add's as desired but never downloads just hangs.  I am using Admin to Login to download station from Radarr.  so neither option works for me, what is the Correct combination, OR will this only work with Beta of Sonarr/Radarr?

**Comment by bakerboy448** [comment]
This is partially fixed in Sonarr stable; and fully fixed in Sonarr develop. 

It is only fixed in Radarr Nightly
