### ISSUE TITLE
Allow import if release title doesn't match series title

### ISSUE THREAD

**Issue by Mystic-Mirage** [Sonarr/Sonarr#4935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I faced a regression introduced in v3.0.7 by https://github.com/Sonarr/Sonarr/commit/2a45b615aeee8d2bd9c34afda77466a2493e2ddc
Sonarr doesn't allow importing a "poorly-named" release anymore, like http://rutor.info/torrent/829861
```
rutor.info_Ходячие мертвецы / The Walking Dead [11x01-12 из 16] (2021) WEBRip 1080p от Kerob | L2
• Found matching series via grab history, but release title doesn't match series title. Automatic import is not possible.
```
Almost all my releases are poorly named just because I use trackers without a strict naming convention. But prior to v3.0.7 that was not a problem.

### Describe the solution you'd like

Add an option to choose between old and new behavior.

### Describe alternatives you've considered

An alternative is restoring an old behavior.

### Anything else?

I'm not the only one who faces this problem. See comments here https://github.com/Sonarr/Sonarr/commit/2a45b615aeee8d2bd9c34afda77466a2493e2ddc

**Comment by markus101** [comment]
Blindly importing things that aren't matched properly was a bug, the current behaviour is how Sonarr was intended to work, but along the way it started importing everything without any sanity checking.

This change was made to deal with cases where an indexer claims a release is for a particular series, usually by TVDB ID, but the series name in the release doesn't match the series title or one of it's aliases so there is chance that the release was incorrectly linked to the wrong series by the indexer. The same applies for indexers (or Jackett) that is renaming releases on their feeds; if release names don't match the final downloaded names there is the potential that it matched to the wrong series.

How was the release named when it was grabbed?
How was the release grabbed, was it grabbed via interactive search or some other way?

**Comment by Mystic-Mirage** [comment]
Currently, due to massive DDoS attack, rutor.info is hidden behind Cloudflare and FlareSolverr doesn't work correctly with it (it passes a challenge but Jackett says that cookie is not valid)

If I remember right, the release was named as it shows in search results on the tracker web UI. Something like:
```
Ходячие мертвецы / The Walking Dead [11x01-12 из 16] (2021) WEBRip 1080p от Kerob | L2
```
It was grabbed via interactive search

**Comment by bakerboy448** [comment]
@Mystic-Mirage no need to guess - Activity => history or History for the episode(s) would have all the details required

**Comment by Mystic-Mirage** [comment]
Thank you. Grabbed release name was:
```
The Walking Dead - S11E01-12 - rus - WEBRip 1080p от Kerob - L2
```
Looks like Jackett changes the release title to match Sonarr naming convention. Sonarr grabs it but after v3.0.7 can't import anymore because the importer uses a release title from a download.

**Comment by josh-sachs** [comment]
I'm going to lead with an opinion, probably to my own detriment, but I can't help it...

Arbitrary changes to the behavior of a critical process like this seems reckless...

I'm running into the issue while rebuilding my library via NZB - Jackett not involved.  Release RARs are named appropriately, but the name of the video inside the RAR is (quite often) arbitrary: 

![image](https://user-images.githubusercontent.com/11616365/158028145-63baf085-42b4-4cbe-a4d5-2b56e13c717b.png)

Is there (or can there be) an option to revert to the old behavior?  

In an effort to preempt: Asking users to resort to additional post-processing to work around a "fix" is asinine.  Whatever you're claiming to protect us from with this "feature" will just be opened wider by inconsistent post-processing implementations.

**Comment by bakerboy448** [comment]
> the name of the video inside the RAR is (quite often) arbitrary:

The download client is responsible for deobfuscating file names. This is not something Sonarr should nor will do. This is not an issue and standard/common usenet practice.

> Is there (or can there be) an option to revert to the old behavior?

No option.  Likely will not be any option.

**Comment by Mystic-Mirage** [comment]
Still looks like a regression to me.
You fight with mismatching releases but kill the import of matching releases. Yes, poorly named but still matching.
I never ever face my indexers giving me the wrong release but I can't import any release now and I am stuck with Sonarr v3.0.6.
I am unable to import any single release because Sonarr stopped importing releases from all of my sources. Not from one, not from two -- from all of them. The import feature is completely broken to me.

**Comment by josh-sachs** [comment]
Yeah, this is a regression.  You're digging your heals in on something sounds nice in principal but is not at all practical...

For example, if you were to hypothetically grab "How I Met Your Mother" - a lot of episodes you would encounter are named with an acronym, HIMYM.

Can you clarify what this is supposed to be protecting users from exactly?

**Comment by bakerboy448** [comment]
> Can you clarify what this is supposed to be protecting users from exactly?

Series that had the wrong id for the series from the tracker.

E.g. the tracker had it with the id of `super great show`  but the file was actually for `show I don't want`

Basically the change needs to stay, but be refined down to be less impactful

**Comment by josh-sachs** [comment]
I understand I'm not a contributor on this project, but still interested in the impetus for the change as it is quite impactful. 

Is there an issue anyone could reference to provide more background?  

Maybe it could shed some light for me as to why an option to just disable this behavior (at least why it is refined to be more practical) would be rejected so quickly.

Thanks

**Comment by Dnkhatri** [comment]
> Because it is generally best practice to avoid options where users can easily break things and easily pick the wrong thing. This is especially true for cases like this were the fix is not options, but to rework the logic.
> 
> Great example is the thousands of users that consistently cannot select the correct Series Type for the show.
> 
> The fix for this issue would be to restrict it to if a grab was ID based or some type of similar reworking.

Breaking the system for the tracker is giving incorrect data is the wrong move. If the website is not good at giving correct metadata you should not be using it. The cardinal rule for torrents is not to change the filename of the release group.  As an example this is the filename the tracker will send


Dr.White S01E02 1080p AMZN WEB-DL DDP2.0 H.264-JPTVclub

This is the actual filename
 
ドクターホワイト Dr.White S01E02 1080p AMZN WEB-DL DDP2.0 H.264-JPTVclub.mkv

With this change the episode wont import even if I have manually searched and added it. I think this is the most tone deaf and idiotic change I have seen. The tracker you use is crap so instead of fixing the tracker you broke sonarr for the rest. It is something similar to all the raving you were doing at the qbittorrent devs about the new update breaking stuff.

**Comment by bakerboy448** [comment]
So you believe every usenet indexer is crap because they occasionally have releases with the wrong tvdbid that is fixed within a few hours or days?  Not to mention the release name has no consideration if the id is used for grabs

Take your unproductive comments elsewhere.

Well aware of the issue.
Well aware of the possibilities to fix it.
And well aware of the problems it's causing.

No ETA on when a fix may be made.
No ETA on when any such fix will be released to main/stable.

Unless one has comments on specifically fixing this or taking the PR effort to fix this - I don't believe this issue requires any further discussion.

Additional comments indicating me too, this is an issue, fix this, etc. are unproductive and unwelcome.

**Comment by UDSHQ** [comment]
Just out of curiosity.. before I pull my hair out. Is this "feature" introduced with 3.0.7 why this won't import? 

![image](https://user-images.githubusercontent.com/26554076/162635880-2a6ead28-469d-47af-8101-52cc72af24aa.png)

**Comment by alaskanrabb** [comment]
dev's have decided that obfuscated releases can go pack sand. the 3.0.8 fix  [e242d24](https://github.com/Drapersniper/Sonarr/commit/e242d2483a87ca2456a2423b17dff69cbb260360) still isn't great


> Just out of curiosity.. before I pull my hair out. Is this "feature" introduced with 3.0.7 why this won't import?
> 
> ![image](https://user-images.githubusercontent.com/26554076/162635906-d0b6eb44-6338-4b35-ba3a-c0911f343e07.png)

**Comment by bakerboy448** [comment]
> dev's have decided that obfuscated releases can go pack sand. the 3.0.8 fix  [e242d24](https://github.com/Drapersniper/Sonarr/commit/e242d2483a87ca2456a2423b17dff69cbb260360) still isn't great
> 
> 
> 
> 
> 
> > Just out of curiosity.. before I pull my hair out. Is this "feature" introduced with 3.0.7 why this won't import?
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/26554076/162635906-d0b6eb44-6338-4b35-ba3a-c0911f343e07.png)
> 
> 
> 
> 

Obfuscated releases are not an issue  at all. They're detected and the folder name is fallen back to.

If you don't want obfuscated file names - that's something your download client must handle. Sonarr has no ability or knowledge to fix that.

**Comment by alaskanrabb** [comment]
It is not falling back to the folder name for me, unless that is an option that is required to be manually enabled. I had zero problems with incorrect series being imported as my indexers would not pull incorrect nzb's when requested by Sonarr. Currently, the only hold up in the automatic flow of files is that Sonarr will not import about 50% of the files it pulls for me. this leaves the the tough choice of 3.0.6 for actual automatic imports or 3.0.8 for the fantastic release group editing feature.

I just added a script to deobfuscate the file name verbatim with release and it will still not import based on grab id, file name, or folder name. this is what you get... 

Found matching series via grab history, but release was matched to series by ID. Automatic import is not possible.

**Comment by bakerboy448** [comment]
Then the tvdbid the indexer reported  does not match the name of the series the file/folder is being detected as. 

Likely the id was for the US series, but that file is named for the UK series.

TVDBid 76808 is "Whose Line Is It Anyway? (US)" https://thetvdb.com/series/whose-line-is-it-anyway

Tvdbid is 78521 "Whose Line is it Anyway" https://thetvdb.com/index.php/series/whose-line-is-it-anyway-uk


Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

**Comment by Dnkhatri** [comment]
@bakerboy448 @markus101 @Taloth 
would it be possible for sonarr if found by id while importing check against the alternate names of the show on tvdb and if they match import the file instead of ignoring.  I know currently the scene alternate names form are used but for many asian shows we have romanji and multiple translated names. With different groups using different names for releasing a show many of these shows are 1 season shows that run over 2 month period then end so submitting multiple alternate show names for dozens of shows every other month is impractical. I am not talking about searching using all those alternate names just about importing when found by id.
Implementing it this way would also allow to import other language named shows when found by id even if not named in English without the names being submitted in the forms. I don't know if tvdb sends the language data with the name if so can be used to set audio language as well but that is a seperare issue.

**Comment by bakerboy448** [comment]
@Dnkhatri 

https://github.com/Sonarr/Sonarr/issues/269 & https://github.com/Sonarr/Sonarr/issues/1234

**Comment by Dnkhatri** [comment]
> @Dnkhatri 
> 
> https://github.com/Sonarr/Sonarr/issues/269 & https://github.com/Sonarr/Sonarr/issues/1234

Both are talking about search I want the alternate name to be used when importing the files. i.e after the files are already found but the name is not the tvdb name after download.

**Comment by markus101** [comment]
How it’s used is irrelevant, any alias is used if available to Sonarr.

Aliases on TheTVDB aware problematic because they may collide with out series, for the foreseeable future request aliases be added on Sonarr’s side.
