### ISSUE TITLE
Some systems prevent us from finding all processes

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#584]
Looks like [FreeNAS] (https://forums.sonarr.tv/t/cant-update-from-gui-on-freenas/5678) and [Arch] (https://forums.sonarr.tv/t/update-via-gui-failing-on-arch-linux/5800) both have the same issue, which will present itself in few cases:

1. When starting up and looking for existing processes
2. Updating, we enumerate all processes to see if the calling Sonarr process is running
3. Updating, we enumerate all processes to see if any Sonarr process is running

We can handle cases 1 and 3 by not caring about it failing and 2 by only getting the process we want when looking if it exists and when we're killing it, only get that process.

**Comment by markus101** [comment]
This is also an issue with mono 3.12 on some systems ([rPi](https://forums.sonarr.tv/t/cant-update-to-2-0-0-3243-jun-18-2015/6064)).

**Comment by markus101** [comment]
Also an issue on [QNAP] (https://forums.sonarr.tv/t/qnap-updater-cant-find-process/5624/11) with mono 4.0

**Comment by markus101** [comment]
This was a mono bug, fixed in 4.0.4.

**Comment by AlanValentine** [comment]
still happens when attempting update, even after freebsd ports gets a mono update today bringing me to 

Mono JIT compiler version 4.2.1 (Stable 4.2.1.102/6dd2d0d Tue Nov 24 21:59:25 UTC 2015)
